import numpy as np
a=np.arange(9,dtype=float).reshape(3,3)
b=np.array([10,10,10])
print(a)
print(b)
print('addition')
print(np.add(a,b))
print('subtraction')
print(np.subtract(b,a))
print('multiply')
print(np.multiply(a,b))
print('divide')
print(np.divide(a,b))
print('dot')
print(np.dot(a,b))
